Do not add the object ID to the JSON representation
The Object ID is added in ParseRESTObjectCommand as part of the URL,
including it in the JSON representation causes the following error
on the server;

exception: Mod on _id not allowed

This fix addresses issue #433